server:
  port: 8762
#spring:
#  profiles: peer2
  
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/    
logging:
  level:
    com.netflix: TRACE